import StoreProvider from '@/redux/StoreProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import 'bulma/css/bulma.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blockchain-based Voting',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>{children}</body>
      </html>
    </StoreProvider>
  )
}
